Repository mezzio/mezzio-authentication-oauth2, pull requests merged in 2024-08, with the labels that each got.

#72 Ensure event listeners have a valid priority when added via the AuthorizationServerFactory
  src/AuthorizationServerFactory.php
  test/AuthorizationServerFactoryTest.php
Labels: Enhancement

#73 Document that redirect_uri is absolute
  README.md
  docs/book/v1/grant/auth_code.md
  docs/book/v1/grant/implicit.md
Labels: Documentation, Enhancement

#74 Fix linting errors
  docs/book/v1/authorization-server.md
Labels: Bug, Documentation

#75 Merge up changes from 2.10.1
  docs/book/v1/authorization-server.md
Labels: Documentation
