Repository mezzio/mezzio-authentication-oauth2, pull requests merged in 2024-11, with the labels that each got.

#78 Update to use PHP 8.1 syntax
  src/AuthorizationHandler.php
  src/OAuth2Adapter.php
  src/Repository/Pdo/ClientRepository.php
  test/Pdo/OAuth2PdoMiddlewareTest.php
Labels: Enhancement

#77 Allow installation of `psr/http-message` `^2.0`
  composer.json
  composer.lock
Labels: dependencies

#79 Upgrade Laminas Dev Dependencies
  composer.json
  composer.lock
  config/oauth2.php
  src/ConfigProvider.php
  src/ConfigTrait.php
  src/Repository/Pdo/ClientRepository.php
Labels: Enhancement, dependencies
